apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq1
  namespace: cp4i-mq
spec:
  license:
    accept: tue
    license: L-RJON-BXUPZ2
    use: NonProduction
  queueManager:
    name: QM1
    storage:
      queueManager:
        type: ephemeral
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.2.2.0-r1
  web:
    enabled: true